export const MOTIVATIONS = [
  "A disciplina é a ponte entre metas e realizações.",
  "Seu corpo é seu templo, cuide bem dele hoje.",
  "Pequenas vitórias diárias levam a grandes resultados.",
  "O único treino ruim é aquele que não aconteceu.",
  "Coma para nutrir seu corpo, não apenas para saciar sua fome.",
  "Seja mais forte que sua melhor desculpa.",
  "O sucesso é a soma de pequenos esforços repetidos dia após dia.",
  "Sua saúde é seu maior investimento.",
  "Não pare até se orgulhar de você mesmo.",
  "Foco, força e muita determinação no dia de hoje!",
  "Acredite em você e tudo será possível.",
  "Mude seus hábitos e mude sua vida.",
  "Cada passo conta. Não importa a velocidade, desde que você não pare.",
  "Sua única competição é quem você foi ontem.",
  "Grandes coisas nunca vêm de zonas de conforto.",
  "Hidrate-se! Água é vida e combustível para seu corpo.",
  "A consistência é o que transforma o comum em extraordinário.",
  "Escolha alimentos que te dão energia, não cansaço.",
  "Hoje é um ótimo dia para ser sua melhor versão.",
  "Motivação faz você começar. Hábito faz você continuar.",
  "Dê o seu melhor hoje e o amanhã será ainda melhor.",
  "Respeite seu ritmo, mas nunca desista de evoluir.",
  "Uma mente sã em um corpo são é o segredo do equilíbrio.",
  "Você é capaz de muito mais do que imagina.",
  "O esforço de hoje é a recompensa de amanhã.",
  "Faça por você, não pelos outros.",
  "Saúde não é sobre o peso que você perde, mas sobre a vida que você ganha.",
  "Comece onde você está. Use o que você tem. Faça o que puder.",
  "O corpo alcança o que a mente acredita.",
  "Nada é impossível para uma mente decidida.",
  "A cada dia, uma nova chance de recomeçar e acertar.",
  "Seja sua própria inspiração.",
  "O segredo do sucesso é começar.",
  "Não espere por condições perfeitas. Crie-as.",
  "Sua vontade deve ser maior que sua vontade de desistir.",
  "Transforme sua dor em poder.",
  "A perfeição não existe, mas a evolução sim.",
  "Respire fundo e siga em frente. Você está no caminho certo.",
  "Honre seu compromisso com sua saúde.",
  "O que você faz hoje determina o seu futuro.",
  "Paciência e persistência são os caminhos do êxito.",
  "Ame-se o suficiente para viver um estilo de vida saudável.",
  "Desafie-se um pouco mais a cada dia.",
  "A meta é ser melhor do que ontem, não melhor que ninguém.",
  "Cada gota de suor te aproxima do seu objetivo.",
  "Não deixe que o ontem ocupe muito do hoje.",
  "Mantenha o foco no que você quer alcançar.",
  "Sua saúde agradece por cada escolha consciente.",
  "Acredite: você está progredindo, mesmo que não veja agora.",
  "Tudo o que você precisa já está dentro de você.",
  "Celebre cada pequena vitória na sua jornada.",
  "Sua jornada é única. Aprecie o processo.",
  "Não conte os dias, faça os dias contarem.",
  "A força não vem da capacidade física, vem de uma vontade indomável.",
  "Alimente sua fé e seus medos morrerão de fome.",
  "Seja resiliente. O caminho é longo, mas vale a pena.",
  "Dê a si mesmo o crédito que você merece.",
  "O impossível é apenas uma opinião.",
  "Siga seus sonhos com coragem e determinação.",
  "Você é o autor da sua própria história de superação.",
  "Otimismo é a chave para abrir as portas do sucesso.",
  "Nunca é tarde para se tornar o que você poderia ter sido.",
  "A maior riqueza é a saúde.",
  "Esqueça as falhas do passado. Foque nas oportunidades do presente.",
  "Seja grato por cada dia e cada oportunidade de evoluir.",
  "Mantenha a cabeça erguida e o coração esperançoso.",
  "Sua dedicação é a semente do seu sucesso.",
  "Acredite no poder da transformação diária.",
  "Seja a mudança que você deseja ver no seu corpo e na sua vida.",
  "Persista, insista e nunca desista.",
  "O seu esforço vale cada segundo.",
  "Foque no progresso, não na perfeição.",
  "Você tem o poder de mudar sua realidade hoje mesmo.",
  "A vida começa no final da sua zona de conforto.",
  "Trabalhe duro em silêncio. Deixe o sucesso ser o seu barulho.",
  "Seja corajoso o suficiente para ser quem você quer ser.",
  "Acredite que o melhor está por vir.",
  "Sua determinação será recompensada.",
  "Faça do seu dia uma obra-prima de escolhas saudáveis.",
  "Você é mais forte do que qualquer desafio que surja no seu caminho.",
  "Mantenha a chama da motivação sempre acesa.",
  "Cada escolha saudável é um ato de amor próprio.",
  "Acredite na sua força interior.",
  "O sucesso não é o final. O fracasso não é fatal. É a coragem de continuar que conta.",
  "Seja positivo, trabalhe duro e faça acontecer.",
  "Sua mente é o limite. Expanda-a.",
  "Tudo o que você quer está do outro lado do medo.",
  "A verdadeira motivação vem de dentro.",
  "Não deixe seus medos decidirem seu futuro.",
  "Seja grato pelo que você tem enquanto trabalha pelo que você quer.",
  "O caminho para o sucesso é sempre em construção.",
  "Viva cada dia com propósito e intenção.",
  "Sua energia é contagiante. Use-a para o bem.",
  "Acredite que hoje será um dia de superação.",
  "Mantenha o equilíbrio entre mente, corpo e alma.",
  "Você é capaz de realizar coisas incríveis.",
  "Nunca desista dos seus sonhos, por mais difíceis que pareçam.",
  "A jornada de mil milhas começa com um único passo.",
  "Seja a melhor versão de si mesmo hoje e sempre.",
  "O sucesso é o resultado da sua preparação e persistência."
];

export const getMotivationOfTheDay = () => {
  const today = new Date();
  const index = (today.getFullYear() * 365 + today.getMonth() * 31 + today.getDate()) % MOTIVATIONS.length;
  return MOTIVATIONS[index];
};
